image: docker.pkg.github.com/s2shape/docker-images/s2shape-test-harness:latest

stages:
  - build
  - test

before_script:
  - dotnet restore -s https://www.myget.org/F/s2/ -s https://api.nuget.org/v3/index.json

build:
  stage: build
  script:
    - dotnet build

test:
  stage: test

  script:
    - ROOT_PROJECT_PATH=$(pwd)
    - dotnet build
    - dotnet publish
    - cd $ROOT_PROJECT_PATH/RedshiftSupplyCollectorLoader/bin/Debug/netcoreapp2.2/publish
    - cp -f /SupplyCollectorDataLoader/SupplyCollectorDataLoader/bin/Debug/netcoreapp2.2/SupplyCollectorDataLoader.runtimeconfig.json .
    - dotnet SupplyCollectorDataLoader.dll -init RedshiftSupplyCollector "Host=$REDSHIFT_HOST;Port=$REDSHIFT_PORT;Database=$REDSHIFT_DB;Username=$REDSHIFT_USER;Password=$REDSHIFT_PASS;Server Compatibility Mode=Redshift"
    - dotnet SupplyCollectorDataLoader.dll -xunit RedshiftSupplyCollector "Host=$REDSHIFT_HOST;Port=$REDSHIFT_PORT;Database=$REDSHIFT_DB;Username=$REDSHIFT_USER;Password=$REDSHIFT_PASS;Server Compatibility Mode=Redshift"
    - cd $ROOT_PROJECT_PATH
    - dotnet test

load_test:
  stage: test

  script:
    - ROOT_PROJECT_PATH=$(pwd)
    - dotnet build
    - dotnet publish
    - cd $ROOT_PROJECT_PATH/RedshiftSupplyCollectorLoader/bin/Debug/netcoreapp2.2/publish
    - cp -f /SupplyCollectorDataLoader/SupplyCollectorDataLoader/bin/Debug/netcoreapp2.2/SupplyCollectorDataLoader.runtimeconfig.json .
    - dotnet SupplyCollectorDataLoader.dll -init RedshiftSupplyCollector "Host=$REDSHIFT_HOST;Port=$REDSHIFT_PORT;Database=$REDSHIFT_DB;Username=$REDSHIFT_USER;Password=$REDSHIFT_PASS;Server Compatibility Mode=Redshift"
    - dotnet SupplyCollectorDataLoader.dll -xunit RedshiftSupplyCollector "Host=$REDSHIFT_HOST;Port=$REDSHIFT_PORT;Database=$REDSHIFT_DB;Username=$REDSHIFT_USER;Password=$REDSHIFT_PASS;Server Compatibility Mode=Redshift"
    - dotnet SupplyCollectorDataLoader.dll -samples RedshiftSupplyCollector "Host=$REDSHIFT_HOST;Port=$REDSHIFT_PORT;Database=$REDSHIFT_DB;Username=$REDSHIFT_USER;Password=$REDSHIFT_PASS;Server Compatibility Mode=Redshift" TestCollection Test1:int,Test2:string,Test3:bool,Test4:double,Test5 1000000
    - cd $ROOT_PROJECT_PATH/RedshiftSupplyCollectorTests/bin/Debug/netcoreapp2.2/publish
    - SupplyCollectorTestHarness -connect "Host=$REDSHIFT_HOST;Port=$REDSHIFT_PORT;Database=$REDSHIFT_DB;Username=$REDSHIFT_USER;Password=$REDSHIFT_PASS;Server Compatibility Mode=Redshift" test_harness.config
